#:schema node_modules/wrangler/config-schema.json
name = "alpenglowguiding"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
RESEND_FROM_EMAIL='contact-form@alpenglowguiding.com'
RESEND_TO_EMAIL='evan@alpenglowguiding.com'
